<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="Acorn" name="ArrayUtilTest" tests="3" failures="2" timestamp="29 Jul 2013 20:20:23 GMT" time="0.021" errors="0">
  <testcase name="testMergeSort" time="0.006" classname="ArrayUtilTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="6">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 6
	at CustomArrayUtil.merge(CustomArrayUtil.java:105)
	at CustomArrayUtil.mergeSort(CustomArrayUtil.java:89)
	at CustomArrayUtil.mergeSort(CustomArrayUtil.java:88)
	at CustomArrayUtil.mergeSort(CustomArrayUtil.java:11)
	at ArrayUtilTest.testMergeSort(ArrayUtilTest.java:8)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 26 stack frames]]>
    </failure>
  </testcase>
  <testcase name="testMergeSort" time="0.0" classname="CustomArrayUtilTest"/>
  <testcase name="testMergeSort" time="0.003" classname="utils.CustomArrayUtilTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;1&amp;gt; but was:&amp;lt;5&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<1> but was:<5>
	at utils.CustomArrayUtilTest.assertEqualsArray(CustomArrayUtilTest.java:22)
	at utils.CustomArrayUtilTest.testMergeSort(CustomArrayUtilTest.java:15)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 31 stack frames]]>
    </failure>
  </testcase>
</testsuite>
